
services:
  - type: web
    name: frontend
    runtime: static
    buildCommand: npm ci; npm run build; node apply-config.js
    staticPublishPath: dist/store-app/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
    - key: API_BASE_URL
      value: http://localhost:3001
    autoDeployTrigger: commit
    rootDir: store-app